# Generated by Django 5.2.5 on 2025-08-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_carros', to='carros.marca')),
            ],
        ),
    ]
