# Generated by Django 5.2.5 on 2025-08-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_carro_cambio_carro_combustivel_carro_cor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='nome',
        ),
    ]
