# Generated by Django 5.2.5 on 2025-08-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_rename_name_marca_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nome',
            new_name='name',
        ),
    ]
