# Generated by Django 5.2.5 on 2025-09-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_rename_nome_marca_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('combustivel', models.CharField(blank=True, max_length=50, null=True)),
                ('cilindradas', models.IntegerField(blank=True, null=True)),
                ('partida_eletrica', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_moto', to='carros.marca')),
            ],
        ),
    ]
