# Generated by Django 5.2.5 on 2025-09-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaMoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Marca',
            new_name='MarcaCarro',
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_moto', to='carros.marcamoto'),
        ),
    ]
